### ISSUE TITLE
Spawning language server with cmd : 'java' failed

### ISSUE THREAD

**Issue by siduck** [williamboman/nvim-lsp-installer#372]
I installed the jdtls server but i get this path issue 

![image](https://user-images.githubusercontent.com/59060246/147756354-44c07042-0605-4a1f-b78e-6946fd45740e.png)

![image](https://user-images.githubusercontent.com/59060246/147756366-3ec41164-0b62-4580-9eb2-6dab9a1db960.png)

**Comment by williamboman** [comment]
Hello! Hm. I will assume `java` is installed on path. What does the LSP log say (`~/.cache/nvim/lsp.log`)?

**Comment by Pranav-Badrinathan** [comment]
OS: Windows 11
Very similar issue on my end, it might provide more info @williamboman. In my case, `clangd` for C is not loading for the same reason:
![image](https://user-images.githubusercontent.com/40524763/147992007-c5c7ea9d-04ef-43d3-87e3-4f95e99529f6.png)
![image](https://user-images.githubusercontent.com/40524763/147992109-0eff75fb-297a-449d-87bb-16e8bd9c8453.png)

I have installed it, as you can see, and it used to work just a couple of days ago. Then I updated the plugin and it seems to have broken the "auto insertion of path to server" as is mentioned in the [README](https://github.com/williamboman/nvim-lsp-installer#:~:text=The%20recommended%20way%20of%20setting%20up%20your%20installed%20servers%20is%20to%20do%20it%20directly%20through%20nvim%2Dlsp%2Dinstaller.%20By%20doing%20so%2C%20nvim%2Dlsp%2Dinstaller%20will%20make%20sure%20to%20inject%20any%20necessary%20properties%20before%20calling%20lspconfig%27s%20setup%20function%20for%20you.).
In the pic of `:LspInfo`, I used to see the path to the installed server in `cmd` instead of `clangd --background-index`, which is what lsp defaults to if no inputs are provided.

In my lsp-installer config, I needed to pass in some custom info for nvim-cmp and sumneko_lua, and as such I followed the [Advanced config: Overriding default lsp options](https://github.com/williamboman/nvim-lsp-installer/wiki/Advanced-Configuration#overriding-the-default-lsp-server-options) basically to the T.

**Comment by Pranav-Badrinathan** [comment]
OS: Windows 11
Very similar issue on my end, it might provide more info @williamboman. In my case, `clangd` for C is not loading for the same reason:
![image](https://user-images.githubusercontent.com/40524763/147992007-c5c7ea9d-04ef-43d3-87e3-4f95e99529f6.png)
![image](https://user-images.githubusercontent.com/40524763/147992109-0eff75fb-297a-449d-87bb-16e8bd9c8453.png)

I have installed it, as you can see, and it used to work just a couple of days ago. Then I updated the plugin and it seems to have broken the "auto insertion of path to server" as is mentioned in the [README](https://github.com/williamboman/nvim-lsp-installer#:~:text=The%20recommended%20way%20of%20setting%20up%20your%20installed%20servers%20is%20to%20do%20it%20directly%20through%20nvim%2Dlsp%2Dinstaller.%20By%20doing%20so%2C%20nvim%2Dlsp%2Dinstaller%20will%20make%20sure%20to%20inject%20any%20necessary%20properties%20before%20calling%20lspconfig%27s%20setup%20function%20for%20you.).
In the pic of `:LspInfo`, I used to see the path to the installed server in `cmd` instead of `clangd --background-index`, which is what lsp defaults to if no inputs are provided.

In my lsp-installer config, I needed to pass in some custom info for nvim-cmp and sumneko_lua, and as such I followed the [Advanced config: Overriding default lsp options](https://github.com/williamboman/nvim-lsp-installer/wiki/Advanced-Configuration#overriding-the-default-lsp-server-options) basically to the T.

EDIT: Just noticed that commit 095ab4e mentions needing to reinstall. lol, sorry for the ping.

**Comment by williamboman** [comment]
Hello @Pranav-Badrinathan! Yeah in the interest of getting rid of some bad historical decisions, unfortunately that commit broke ltex and clangd installations. I'm working on #340 to help mitigate this, so that pulling a new version of the plugin should have minimal (if any) effects on your already installed servers (any changes would only be applied once you update the servers themselves).

> EDIT 2: If you are here now, and don't mind me asking, what does "it now provides an amended PATH" mean? And why is `cmd` not used anymore? I mean, it is a good thing as it opens up cmd for other flags that one might want to send, but what does PATH mean?

An amended PATH is a bit lazy phrasing from my part. But in essence; What allows a piece of software to identify where an executable is located on the system is the [PATH variable](https://en.wikipedia.org/wiki/PATH_(variable)). All server configurations in lspconfig assumes that the server executable exists somewhere in PATH. However, this plugin will not install server executables to any location that is in PATH (you can of course manually add these locations to your PATH, but that's very tedious).

So, how this plugin worked prior to that commit was to provide a `cmd` to lspconfig which contained the absolute path to the locally installed server executable file (for example `~/.local/share/nvim/lsp_servers/tsserver/node_modules/.bin/tsserver`). Because the `cmd` was overridden in its entirety, we'd also have to make sure to provide any necessary extra arguments (like `--stdio --hostPID=x`). For these we'd essentially just mirror what was defined lspconfig. This caused duplication across the two plugins but also a drift as changes are made.

neovim uses [libuv](https://github.com/libuv/libuv) for a lot of things under the hood. For example, it uses `uv_spawn` (`vim.loop.spawn`) to start language servers. When calling `uv_spawn` with a command, for example `vim.loop.spawn("tsserver")`, it will try to locate the actual location of the `tsserver` executable by using the PATH environment variable. Due to some recent changes made in core neovim, we can now make use of this in this plugin to hopefully help mitigate some of the problems mentioned above!

```diff
- cmd: ~/.local/share/nvim/lsp_servers/tsserver/node_modules/.bin/tsserver --stdio
+ cmd: tsserver --stdio <-- now provided by lspconfig
- PATH: /usr/bin
+ PATH: ~/.local/share/nvim/lsp_servers/tsserver/node_modules/.bin:/usr/bin
```

**Comment by Pranav-Badrinathan** [comment]
>So, how this plugin worked prior to that commit was to provide a `cmd` to `lspconfig` which contained the absolute path to the locally installed server executable file. Because the `cmd` was *overridden in its entirety*...
Glad this is not the case anymore.😌 I personally tried passing flags via `cmd` and found out that doing so breaks the system. 

>In essence, we tell lspconfig to start each server with a custom PATH environment variable that will allow uv_spawn to find it.
A more elegant solution that does not really require any user interaction, solves code duplication between plugins, and makes `cmd` accessible to the user. Nice.

Thanks for your reply!

**Comment by siduck** [comment]
> ~/.cache/nvim/lsp.log

![image](https://user-images.githubusercontent.com/59060246/148310993-fe23a170-2f2c-47d6-b95f-5379c37f595c.png)

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/148311032-0e2a7bac-cafb-4dd8-93ba-2edf0b90d8b3.png)
I still get the same error :c

**Comment by williamboman** [comment]
What does the following produce?

```
$ java -version
$ find ~/.local/share/nvim/lsp_servers/jdtls -iname '*equinox*'
```

**Comment by siduck** [comment]
> What does the following produce?
> 
> ```
> $ java -version
> $ find ~/.local/share/nvim/lsp_servers/jdtls -iname '*equinox*'
> ```

i dont work with java, someone using nvchad had this issue so i tested it myself. i thought only java lsp was required but java is needed too?

**Comment by williamboman** [comment]
Yes a JRE is needed as it runs .jar files!

**Comment by williamboman** [comment]
I pushed 60e411d146e7d6892732195cd3f9c0ab7bb76383 which hopefully makes this easier to catch earlier.

**Comment by siduck** [comment]
@williamboman i no longer get the path issue but the lsp starts with this 

![image](https://user-images.githubusercontent.com/59060246/148664571-d0bc2a13-21f2-41c5-b2ad-2153b3def2f3.png)

**Comment by siduck** [comment]
works!
![image](https://user-images.githubusercontent.com/59060246/148664579-f8200595-ee11-4d15-b6ac-afaf571ce769.png)
![image](https://user-images.githubusercontent.com/59060246/148664581-f9b41252-31b0-4fa6-bbed-e2fb1b92fc25.png)

thanks a lot @williamboman

**Comment by williamboman** [comment]
As for the progress messages: the way jdtls has implemented progress reporting isn't per the LSP spec, so it just prints the messages by default.

I've got [this](https://github.com/williamboman/nvim-config/blob/main/lua/wb/lsp/init.lua#L145-L212) in my personal config, which maps their custom progress reporting to the `$/progress` handler (which I've hooked up to lualine, see below). I'll try to see if there's interest to include this upstream in lspconfig.

<img width="1180" alt="Screenshot 2022-01-09 at 01 35 11" src="https://user-images.githubusercontent.com/6705160/148664618-02f4c6e1-5f6e-46ae-b313-5b1c50f285b3.png">

**Comment by siduck** [comment]
@williamboman one more thing, the icons used in the lspinstaller's gif in the readme look nice but the default ones look bad 

![image](https://user-images.githubusercontent.com/59060246/148664661-cd1cccb7-5167-465d-b9d9-f86c899a6f44.png)

could you make these icons default?

![image](https://user-images.githubusercontent.com/59060246/148664668-4abab888-8267-435c-9312-944df65d5b2d.png)

**Comment by williamboman** [comment]
Yeah the default ones are pretty bad. The thing is that the icons I use in the recording is part of the nerd font collection. If your font is not compatible with it, it will either render some other character or nothing at all. It'll have to be an icon within the standard unicode range. Happy to take suggestions for such candidates

**Comment by nhoknakroz** [comment]
Hi @williamboman, what font are you using? It look very good!

**Comment by siduck** [comment]
> Hi @williamboman, what font are you using? It look very good!

jetbrainsmono probably

**Comment by williamboman** [comment]
Correct! Jet Brains Mono ([Nerdfont variant](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/JetBrainsMono/Ligatures/Regular/complete/JetBrains%20Mono%20Regular%20Nerd%20Font%20Complete%20Mono.ttf))
