### ISSUE TITLE
ltex executable not found

### ISSUE THREAD

**Issue by ruanyouxing** [williamboman/nvim-lsp-installer#425]
### Problem description

I install ltex for LaTeX, but first, it have no attached server when i open a .tex file
![image](https://user-images.githubusercontent.com/87190231/149523888-56e20726-61b0-4670-9fc4-7b737db2107e.png)
i tried require('lspconfig').ltex.setup{}
![image](https://user-images.githubusercontent.com/87190231/149523977-f75c70e9-44d6-4ca2-b5e6-fcfce5e28aea.png)
When i run LspInfo:
![image](https://user-images.githubusercontent.com/87190231/149524256-08e9a946-389e-42cb-ba50-e67cb4be74bb.png)

### Neovim version (>= 0.6)

NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

### Operating system/version

Linux 

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

ltex 

### Actual behavior

ltex started 

### Expected behavior

ltex installed but didn't work,maybe no executable 

### LspInstallInfo output

```shell
Installed servers: 
bashls 
clangd 
grammarly
hls
html 
jdtls
jsonls
ltex
pyright
rust_analyzer
sumneko_lua
tsserver
```

### Installation log

```shell
[INFO  Sat 05 Dec 2021 10:28:00 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:551: Starting install server_name="clangd", requested_version=""
[INFO  Sat 05 Dec 2021 10:28:58 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:570: Installation completed server_name="clangd", success=true
[INFO  Sat 05 Dec 2021 10:28:58 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:551: Starting install server_name="clangd", requested_version=""
[INFO  Sat 05 Dec 2021 10:30:48 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:551: Starting install server_name="tsserver", requested_version=""
[INFO  Sat 05 Dec 2021 10:30:57 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:570: Installation completed server_name="clangd", success=true
[INFO  Sat 05 Dec 2021 10:31:59 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:570: Installation completed server_name="tsserver", success=true
[INFO  Sat 05 Dec 2021 10:32:22 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:551: Starting install server_name="jdtls", requested_version=""
[INFO  Sat 05 Dec 2021 10:34:10 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:570: Installation completed server_name="jdtls", success=true
[INFO  Sat 05 Dec 2021 10:34:39 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:551: Starting install server_name="sumneko_lua", requested_version=""
[INFO  Sat 05 Dec 2021 10:34:50 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:570: Installation completed server_name="sumneko_lua", success=true
[INFO  Sun 06 Dec 2021 07:32:56 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:551: Starting install server_name="pyright", requested_version=""
[INFO  Sun 06 Dec 2021 07:33:25 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:570: Installation completed server_name="pyright", success=true
[INFO  Mon 07 Dec 2021 06:30:43 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:551: Starting install server_name="jdtls", requested_version=""
[INFO  Mon 07 Dec 2021 06:31:12 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:570: Installation completed server_name="jdtls", success=true
[INFO  Mon 07 Dec 2021 06:53:30 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:551: Starting install server_name="jdtls", requested_version=""
[INFO  Mon 07 Dec 2021 06:53:56 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:570: Installation completed server_name="jdtls", success=true
[ERROR Thu 10 Dec 2021 11:34:12 AM UTC] ...rt/nvim-lsp-installer/lua/nvim-lsp-installer/process.lua:156: Failed to spawn process. cmd="composer", err="ENOENT: no such file or directory"
[ERROR Thu 10 Dec 2021 11:34:12 AM UTC] ...rt/nvim-lsp-installer/lua/nvim-lsp-installer/process.lua:156: Failed to spawn process. cmd="php", err="ENOENT: no such file or directory"
[INFO  Tue 22 Dec 2021 08:13:51 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:560: Starting install server_name="jdtls", requested_version=""
[INFO  Tue 22 Dec 2021 08:13:51 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:579: Installation completed server_name="jdtls", success=false
[INFO  Tue 22 Dec 2021 08:14:16 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:560: Starting install server_name="jdtls", requested_version=""
[ERROR Tue 22 Dec 2021 08:25:38 AM UTC] ...rt/nvim-lsp-installer/lua/nvim-lsp-installer/process.lua:156: Failed to spawn process. cmd="composer", err="ENOENT: no such file or directory"
[ERROR Tue 22 Dec 2021 08:25:38 AM UTC] ...rt/nvim-lsp-installer/lua/nvim-lsp-installer/process.lua:156: Failed to spawn process. cmd="php", err="ENOENT: no such file or directory"
[INFO  Tue 22 Dec 2021 08:29:18 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:560: Starting install server_name="ccls", requested_version=""
[INFO  Tue 22 Dec 2021 08:29:18 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:560: Starting install server_name="clangd", requested_version=""
[INFO  Tue 22 Dec 2021 08:29:18 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:560: Starting install server_name="jdtls", requested_version=""
[INFO  Tue 22 Dec 2021 08:38:10 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:579: Installation completed server_name="clangd", success=true
[INFO  Tue 22 Dec 2021 08:38:12 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:579: Installation completed server_name="jdtls", success=true
[INFO  Tue 22 Dec 2021 09:11:19 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:579: Installation completed server_name="ccls", success=false
[INFO  Wed 23 Dec 2021 05:00:16 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:560: Starting install server_name="sumneko_lua", requested_version=""
[INFO  Wed 23 Dec 2021 05:00:23 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:579: Installation completed server_name="sumneko_lua", success=true
[INFO  Sun 27 Dec 2021 11:03:32 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:562: Starting install server_name="ccls", requested_version=""
[INFO  Sun 27 Dec 2021 11:03:32 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:562: Starting install server_name="clangd", requested_version=""
[INFO  Sun 27 Dec 2021 11:03:32 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:562: Starting install server_name="bashls", requested_version=""
[INFO  Sun 27 Dec 2021 11:03:32 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:562: Starting install server_name="grammarly", requested_version=""
[INFO  Sun 27 Dec 2021 11:04:26 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:581: Installation completed server_name="clangd", success=true
[INFO  Sun 27 Dec 2021 11:04:27 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:562: Starting install server_name="sumneko_lua", requested_version=""
[INFO  Sun 27 Dec 2021 11:04:32 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:581: Installation completed server_name="grammarly", success=true
[INFO  Sun 27 Dec 2021 11:04:32 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:562: Starting install server_name="vimls", requested_version=""
[INFO  Sun 27 Dec 2021 11:04:40 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:581: Installation completed server_name="sumneko_lua", success=true
[INFO  Sun 27 Dec 2021 11:04:48 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:581: Installation completed server_name="bashls", success=true
[INFO  Sun 27 Dec 2021 11:04:50 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:581: Installation completed server_name="vimls", success=true
[INFO  Sun 27 Dec 2021 11:07:03 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:562: Starting install server_name="pyright", requested_version=""
[INFO  Sun 27 Dec 2021 11:07:23 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:581: Installation completed server_name="pyright", success=true
[INFO  Sun 27 Dec 2021 11:17:45 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="bashls", requested_version=""
[INFO  Sun 27 Dec 2021 11:18:16 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="bashls", success=true
[INFO  Sun 27 Dec 2021 11:28:53 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="bashls", requested_version=""
[INFO  Sun 27 Dec 2021 11:29:20 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="bashls", success=true
[INFO  Sun 27 Dec 2021 11:35:28 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="clangd", requested_version=""
[INFO  Sun 27 Dec 2021 11:35:28 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="ccls", requested_version=""
[INFO  Sun 27 Dec 2021 11:36:42 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="clangd", success=true
[INFO  Sun 27 Dec 2021 11:37:21 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="clangd", requested_version=""
[INFO  Sun 27 Dec 2021 11:37:21 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="cmake", requested_version=""
[INFO  Sun 27 Dec 2021 11:37:21 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="vimls", requested_version=""
[INFO  Sun 27 Dec 2021 11:37:34 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="vimls", success=true
[INFO  Sun 27 Dec 2021 11:37:34 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="sumneko_lua", requested_version=""
[INFO  Sun 27 Dec 2021 11:37:47 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="sumneko_lua", success=true
[INFO  Sun 27 Dec 2021 11:37:47 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="jdtls", requested_version=""
[INFO  Sun 27 Dec 2021 11:37:59 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="clangd", success=true
[INFO  Sun 27 Dec 2021 11:38:22 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="cmake", success=true
[INFO  Sun 27 Dec 2021 11:38:52 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="jdtls", success=true
[INFO  Sun 27 Dec 2021 12:01:51 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="pyright", requested_version=""
[INFO  Sun 27 Dec 2021 12:02:14 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="pyright", success=true
[INFO  Sun 27 Dec 2021 12:04:47 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="grammarly", requested_version=""
[INFO  Sun 27 Dec 2021 12:05:16 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="grammarly", success=true
[INFO  Sun 27 Dec 2021 03:41:45 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="ccls", requested_version=""
[INFO  Sun 27 Dec 2021 04:20:48 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="ccls", success=false
[INFO  Sun 27 Dec 2021 04:59:32 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="ccls", requested_version=""
[INFO  Sun 27 Dec 2021 05:10:28 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="rust_analyzer", requested_version=""
[INFO  Sun 27 Dec 2021 05:10:38 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="rust_analyzer", success=true
[INFO  Sun 27 Dec 2021 06:22:00 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="ccls", success=false
[INFO  Sun 27 Dec 2021 06:23:44 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="ccls", requested_version=""
[INFO  Sun 27 Dec 2021 07:01:46 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="ccls", success=false
[INFO  Sun 27 Dec 2021 07:57:59 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="clangd", requested_version=""
[ERROR Sun 27 Dec 2021 07:58:53 PM UTC] ...rt/nvim-lsp-installer/lua/nvim-lsp-installer/process.lua:156: Failed to spawn process. cmd="composer", err="ENOENT: no such file or directory"
[ERROR Sun 27 Dec 2021 07:58:54 PM UTC] ...rt/nvim-lsp-installer/lua/nvim-lsp-installer/process.lua:156: Failed to spawn process. cmd="php", err="ENOENT: no such file or directory"
[INFO  Sun 27 Dec 2021 08:02:56 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="ccls", requested_version=""
[INFO  Sun 27 Dec 2021 08:08:01 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="clangd", requested_version=""
[INFO  Sun 27 Dec 2021 08:10:50 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="clangd", success=true
[INFO  Sun 27 Dec 2021 08:27:03 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="ccls", requested_version=""
[INFO  Sun 27 Dec 2021 09:09:16 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="ccls", success=false
[INFO  Sun 27 Dec 2021 09:39:12 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="ccls", requested_version=""
[INFO  Sun 27 Dec 2021 10:23:37 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="ccls", success=false
[INFO  Sun 27 Dec 2021 11:01:01 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="ccls", requested_version=""
[INFO  Sun 27 Dec 2021 11:03:45 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="jsonls", requested_version=""
[INFO  Sun 27 Dec 2021 11:40:52 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="ccls", success=false
[INFO  Mon 28 Dec 2021 07:28:28 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="tsserver", requested_version=""
[INFO  Mon 28 Dec 2021 07:28:53 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="tsserver", success=true
[INFO  Tue 29 Dec 2021 03:36:18 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="sumneko_lua", requested_version=""
[INFO  Tue 29 Dec 2021 03:36:33 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="sumneko_lua", success=true
[INFO  Wed 30 Dec 2021 12:24:10 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="rust_analyzer", requested_version=""
[INFO  Wed 30 Dec 2021 12:24:26 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="rust_analyzer", success=true
[INFO  Wed 30 Dec 2021 12:27:17 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="sumneko_lua", requested_version=""
[INFO  Wed 30 Dec 2021 12:27:23 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="sumneko_lua", success=true
[INFO  Wed 30 Dec 2021 12:31:16 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="bashls", requested_version=""
[INFO  Wed 30 Dec 2021 12:31:16 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="pyright", requested_version=""
[INFO  Wed 30 Dec 2021 12:31:16 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="jdtls", requested_version=""
[INFO  Wed 30 Dec 2021 12:31:16 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="clangd", requested_version=""
[INFO  Wed 30 Dec 2021 12:31:47 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="pyright", success=true
[INFO  Wed 30 Dec 2021 12:31:47 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="grammarly", requested_version=""
[INFO  Wed 30 Dec 2021 12:32:23 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="jdtls", success=true
[INFO  Wed 30 Dec 2021 12:32:23 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="tsserver", requested_version=""
[INFO  Wed 30 Dec 2021 12:32:25 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="bashls", success=true
[INFO  Wed 30 Dec 2021 12:32:33 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="clangd", success=true
[INFO  Wed 30 Dec 2021 12:32:34 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="grammarly", success=true
[INFO  Wed 30 Dec 2021 12:33:01 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="tsserver", success=true
[INFO  Wed 30 Dec 2021 12:34:28 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="jsonls", requested_version=""
[INFO  Wed 30 Dec 2021 12:35:04 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="jsonls", success=true
[INFO  Sat 02 Jan 2022 05:17:39 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="ccls", requested_version=""
[INFO  Sat 02 Jan 2022 05:50:54 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="ccls", requested_version=""
[INFO  Sat 02 Jan 2022 06:32:01 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="ccls", success=false
[INFO  Sat 02 Jan 2022 06:33:31 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="eslint", requested_version=""
[INFO  Sat 02 Jan 2022 06:38:34 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="eslint", success=true
[INFO  Thu 31 Dec 2021 04:22:26 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="tsserver", requested_version=""
[INFO  Thu 31 Dec 2021 04:23:00 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="tsserver", success=true
[INFO  Thu 31 Dec 2021 04:23:14 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="eslint", requested_version=""
[INFO  Thu 31 Dec 2021 04:23:54 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="eslint", success=true
[INFO  Mon 11 Jan 2022 10:32:10 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="tsserver", requested_version=""
[INFO  Mon 11 Jan 2022 10:33:23 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="tsserver", requested_version=""
[INFO  Mon 11 Jan 2022 10:33:47 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="tsserver", requested_version=""
[INFO  Mon 11 Jan 2022 10:34:27 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="tsserver", success=true
[INFO  Mon 11 Jan 2022 10:48:56 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="tsserver", requested_version=""
[INFO  Mon 11 Jan 2022 10:49:39 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="tsserver", success=true
[INFO  Tue 12 Jan 2022 02:21:49 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="texlab", requested_version=""
[INFO  Tue 12 Jan 2022 02:22:00 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="texlab", success=true
[INFO  Tue 12 Jan 2022 02:26:12 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="texlab", requested_version=""
[INFO  Tue 12 Jan 2022 02:26:23 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="texlab", success=true
[ERROR Tue 12 Jan 2022 06:38:03 PM UTC] ...rt/nvim-lsp-installer/lua/nvim-lsp-installer/process.lua:156: Failed to spawn process. cmd="composer", err="ENOENT: no such file or directory"
[ERROR Tue 12 Jan 2022 06:38:03 PM UTC] ...rt/nvim-lsp-installer/lua/nvim-lsp-installer/process.lua:156: Failed to spawn process. cmd="php", err="ENOENT: no such file or directory"
[INFO  Wed 13 Jan 2022 04:09:46 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="ccls", requested_version=""
[WARN  Wed 13 Jan 2022 04:09:47 AM UTC] ...-installer/lua/nvim-lsp-installer/installers/context.lua:22: Failed to fetch URL "https://api.github.com/repos/llvm/llvm-project/releases/latest". stderr="curl: (6) Could not resolve host: api.github.com\n"
[INFO  Wed 13 Jan 2022 04:09:47 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="ccls", success=false
[INFO  Wed 13 Jan 2022 04:10:40 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="ccls", requested_version=""
[INFO  Wed 13 Jan 2022 04:54:34 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="ccls", success=false
[INFO  Thu 14 Jan 2022 04:18:46 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="ccls", requested_version=""
[INFO  Thu 14 Jan 2022 04:59:33 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="ccls", success=false
[INFO  Thu 14 Jan 2022 06:01:29 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="ccls", requested_version=""
[INFO  Thu 14 Jan 2022 06:39:12 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="ccls", success=false
[INFO  Thu 14 Jan 2022 12:30:06 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="hls", requested_version=""
[INFO  Thu 14 Jan 2022 12:31:58 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="hls", success=true
[INFO  Fri 15 Jan 2022 11:45:02 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="texlab", requested_version=""
[INFO  Fri 15 Jan 2022 11:45:11 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="texlab", success=true
[INFO  Fri 15 Jan 2022 11:46:10 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="ltex", requested_version=""
[INFO  Fri 15 Jan 2022 11:48:24 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="ltex", success=true
[INFO  Fri 15 Jan 2022 11:49:50 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="html", requested_version=""
[INFO  Fri 15 Jan 2022 11:50:37 AM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="html", success=true
[INFO  Fri 15 Jan 2022 07:52:08 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="ltex", requested_version=""
[INFO  Fri 15 Jan 2022 07:54:09 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="ltex", success=true
[INFO  Fri 15 Jan 2022 08:09:02 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="texlab", requested_version=""
[INFO  Fri 14 Jan 2022 08:09:10 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="texlab", success=true
[INFO  Fri 14 Jan 2022 08:10:44 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="ltex", requested_version=""
[INFO  Fri 14 Jan 2022 08:13:08 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="ltex", requested_version=""
[INFO  Fri 14 Jan 2022 08:13:32 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:580: Starting install server_name="ltex", requested_version=""
[INFO  Fri 14 Jan 2022 08:16:53 PM UTC] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:599: Installation completed server_name="ltex", success=true
```

### Healthcheck

```shell
all ok
```

**Comment by williamboman** [comment]
Hello! How do you set up the servers in your config? Does it work if you use the [example setup snippet in the README](https://github.com/williamboman/nvim-lsp-installer#setup)? Make sure you don't call `require('lspconfig').ltex.setup{}` anywhere, you need to set things up via nvim-lsp-installer for the neovim LSP client to be able to locate the executable.

**Comment by ruanyouxing** [comment]
My config here
![image](https://user-images.githubusercontent.com/87190231/149597049-5b3c0a86-c4ce-4dbc-86bc-d04f4471706c.png)

**Comment by williamboman** [comment]
It seems like you're missing the setup part. That snippet will only automatically install those servers if they're not already installed.

Try adding the following to your config

```lua
local lsp_installer = require("nvim-lsp-installer")

-- Register a handler that will be called for all installed servers.
-- Alternatively, you may also register handlers on specific server instances instead (see example below).
lsp_installer.on_server_ready(function(server)
    local opts = {}

    -- (optional) Customize the options passed to the server
    -- if server.name == "tsserver" then
    --     opts.root_dir = function() ... end
    -- end

    -- This setup() function is exactly the same as lspconfig's setup function.
    -- Refer to https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md
    server:setup(opts)
end)
```

**Comment by ruanyouxing** [comment]
the server worked maybe, but it multiples itself
![image](https://user-images.githubusercontent.com/87190231/149629348-1bf008d8-ab22-4928-bb26-ef6c7739034a.png)

**Comment by ruanyouxing** [comment]
it still doesn't work when i edit

**Comment by williamboman** [comment]
> the server worked maybe, but it multiples itself

Make sure you don't call `lsp_installer.on_server_ready()` more than one time. It seems like you're setting up the server multiple times (it should only be done once).

> it still doesn't work when i edit

What more exactly doesn't work? What's the behavior you're expecting?

**Comment by ruanyouxing** [comment]
yes i just call it once

**Comment by ruanyouxing** [comment]
![image](https://user-images.githubusercontent.com/87190231/149758668-092a4dea-eef0-4f6d-9ac2-42f444e6643e.png)

**Comment by williamboman** [comment]
@ruanyouxing I found your public nvim files and [opened a PR](https://github.com/ruanyouxing/nvim/pull/1) that should fix the multiplication issue

**Comment by ruanyouxing** [comment]
> @ruanyouxing I found your public nvim files and [opened a PR](https://github.com/ruanyouxing/nvim/pull/1) that should fix the multiplication issue

thank you

**Comment by williamboman** [comment]
To me it seems like this can now be closed

**Comment by timoleistner** [comment]
Somehow I still have the same issue.
My minimal configurations are as follows

```
local servers = {
    ltex = {},
}
for server, config in pairs(servers) do
    local server_available, requested_server = lsp_installer_servers.get_server(server)
    if server_available and not requested_server:is_installed() then
        requested_server:install()
    end
    lspconfig[server].setup(vim.tbl_deep_extend("force", {
        on_attach = on_attach,
        capabilities = create_capabilities(),
        flags = {
            debounce_text_changes = 150,
        },
    }, config))
end
```
Let me know if you need more info on my configuration.

This works with all other servers I have installed and somehow ltex wont find the correct binary.
If I add the specific path (`$HOME/.local/share/nvim/lsp_servers/ltex/ltex-ls/bin`) to my PATH environment variable it works but I would like to avoid that and have the correct path included with this plugin.
